# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_bIZxaH_Vvczvy0Dj9BAiVniRDIIRve
"""

# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#  Loading the dataset
iris_data = pd.read_csv('Iris.csv')

# Exploring  the dataset
print(iris_data.head())  # Displaying the first few rows of the dataset
print(iris_data.info())  # Getting information about the dataset

# Splitting the dataset into features and target variable
X = iris_data.drop('Species', axis=1)  # Features (sepal length, sepal width, petal length, petal width)
y = iris_data['Species']  # Target variable

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Choosing a model and training it
model = KNeighborsClassifier(n_neighbors=3)  # Using K-Nearest Neighbors classifier
model.fit(X_train, y_train)

# Evaluating the model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""**VISUALISATION**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Pairplot to visualize pairwise relationships in the dataset
sns.pairplot(iris_data, hue='Species')
plt.show()

# Boxplot to visualize the distribution of each feature by species
plt.figure(figsize=(10, 6))
sns.boxplot(x='Species', y='SepalLengthCm', data=iris_data)
plt.title('Sepal Length by Species')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Species', y='SepalWidthCm', data=iris_data)
plt.title('Sepal Width by Species')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Species', y='PetalLengthCm', data=iris_data)
plt.title('Petal Length by Species')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Species', y='PetalWidthCm', data=iris_data)
plt.title('Petal Width by Species')
plt.show()